### ISSUE TITLE
Get this error in the HA logs

### ISSUE THREAD

**Issue by dylanmcdermott** [edwork/homeassistant-peloton-sensor#12]
After copying the custom components folder in, updating config, and restarting 

Platform error sensor.peloton - No module named 'pylotoncycle'

**Comment by edwork** [comment]
Hello,  

I think this is an issue with the way the modules are being imported. I'm looking at [this as a reference](https://github.com/xerxes87/pyfujitsu_for_homeassistant/pull/2/commits/4ecee9c7d7822b0cbe6a81e1877ea1927413747a) and think I need to refactor the importing so that pre-restart validation works out. 

In the meantime simply force restarting HomeAssistant should do the trick as it will import just find during startup. I'll leave this issue open as I work out the changes. 

Thanks!  
Ed

**Comment by edwork** [comment]
Nope - as long as you have `custom_components/peloton` in your HASS Config Folder it will pull the dependencies (despite the warning). The `manifest.json` file tells HASS what python modules need loaded upon startup.  

I believe this issue is due to the `import pylotoncycle` statement rather than importing `pylotoncycle.PylotonCycle` via `import PylotonCycle from pylotoncycle` - but that's just a working theory until I can quickly make the changes and test. When I test my method has been to start/stop the server service directly so I never end up seeing this issue. 

Thanks again for the heads up. Changes are incoming. In the meantime I highly recommend using [HACS](https://hacs.xyz/) where I've published the package. This makes it easy to quickly update the integration when fixes are pushed out. Just a simple click and restart. 

Hope this helps!  
Ed

**Comment by dylanmcdermott** [comment]
Installing through HACS worked great, you should update the github readme to show that is an option :) Thank you! cool add in!

**Comment by frazzyfin** [comment]
@edwork I can't seem to find the app when searching 'peloton' in HACS.

**Comment by edwork** [comment]
Hey All - this is still on my radar.  

It's been a while since I released this, and either something has changed or I still need to add the right entry to the main HACS project (more likely the latter). Both this and instructions in the README would be great additions. 

I'll work on this soon™

**Comment by edwork** [comment]
Closing this issue in favor of  #18 (HACS Support).
