### ISSUE TITLE
Warning logged every 30 seconds after updating to `0.6.0`

### ISSUE THREAD

**Issue by mdegat01** [edwork/homeassistant-peloton-sensor#26]
After updating to `0.6.0` and restarting I now see a warning in my logs every 30 seconds from my peloton sensors (seems like every time they update) I turned on debug logging as well for this component so here's the logs I get each sensor update:

```
2021-12-20 11:17:13 DEBUG (SyncWorker_15) [custom_components.peloton.sensor] Logging in and setting up session to the Peloton API
2021-12-20 11:17:15 DEBUG (SyncWorker_15) [custom_components.peloton.sensor] Updating Primary State
2021-12-20 11:17:15 DEBUG (SyncWorker_15) [custom_components.peloton.sensor] Updating Extra State Attributes
2021-12-20 11:17:15 WARNING (SyncWorker_15) [custom_components.peloton.sensor] Error on parsing State Attributes, something in the API may have changed
```

The sensors seem to be working fine I think? Honestly I'm not sure, I haven't really looked that closely at them in a while. The main thing I do with them is when state is `Active` and `attributes.Workout Type` is `cycling` or `bike_bootcamp` I use that as a room presence indicator (i.e. someone is using the bike). That attribute still seems to be there, if others are missing I wouldn't really know.  Here's the full state of my sensor, if something looks like it is missing then let me know:
![Screen Shot 2021-12-20 at 11 23 49 AM](https://user-images.githubusercontent.com/2037026/146799675-383fbc18-f480-4a1f-8acd-92d76bcb06bf.png)

I can set log level of this component to `error` if this warning is ignorable to prevent it from spamming my logs but ideally it would be either fixed or removed somehow since I like logging at `warning` level in general.

**Comment by edwork** [comment]
Yes - these Logger statements are too aggressive. I'll work on a hotfix, feel free to submit a PR in the meantime if you want to enhance logging in other areas too. 

I do think there's an additional error that in already aware of. Since I've only really run this for bike sessions I've only looked at attributes for bike sessions. When meditating, boxing, walking, etc the attributes I'm explicitly asking for are missing causing the exception to be raised. When the exception is called it also stops looking for more attributes. 

To fix this the attribute section needs rebased to tolerate failed attribute lookups and lookup different attributes for different types of workouts.

**Comment by mdegat01** [comment]
Ah yea ok I see how this works. My sensor is breaking [at L115](https://github.com/edwork/homeassistant-peloton-sensor/blob/master/custom_components/peloton/sensor.py#L115) because my last workout was a stretch and those don't have a distance summary. My wife's is breaking [at L117](https://github.com/edwork/homeassistant-peloton-sensor/blob/master/custom_components/peloton/sensor.py#L117) because although here last workout was cycling we don't have a heart monitor so those metrics are missing.

I can probably put in a quick fix for this in a bit. Although I think long-term as #25 progresses you might want to think about bumping these attributes out into their own sensors. That would give a few benefits:

1. Users can individually disable sensors they don't need or can't use (like the heart beat one for me)
2. More of this data can be easily exposed to users. I had no idea how much data was in this API until I started poking around for this bug. If each field was its own sensor its easier to expose far more of it since each user can just disable the sensors they don't care about. Can't really do that when the data becomes attributes on one sensor.
3. Fits better with the new features around long-term statistics HA has been pushing, could be handy to see those kind of metrics for your peloton data over time.

**Comment by mdegat01** [comment]
> lookup different attributes for different types of workouts

Actually FYI, this isn't safe. You can have a peloton membership without owning any of their equipment if you just like the classes. We did that for a while before we decided to get a bike, just did the classes using the app while on some random bike we got off facebook marketplace. When you do a class using the app like that it can't track most of the metrics like "Resistance", "Calories", "Speed", etc. even though we did a cycling class.

The simplest thing is obviously just to make it very fault-tolerant but then you won't get warnings when the API changes like you want. Alternatively you'd have to consider not just the type of exercise but also add some new config options like:

1. Do you have a heart rate monitor connected?
2. What peloton-connected equipment do you have? Bike, treadmill, etc.

It would be pretty tough honestly. There's lot of variations to consider if trying for true completeness. What if they have a bike and a treadmill but only one has a heart rate monitor? What are the API differences between V1 and V2, enough that you have to separately prompt for version? etc.

**Comment by tony1661** [comment]
Hi @mdegat01 I've issued a PR to fix the logs when you do not have a heart rate monitor. If @edwork accepts them then you can use the following in your config:

```
sensor:
  - platform: peloton
    username: tony1661
    password: ********
    hrmonitor: false
```

Let me know if that helps with your wife's issue on Line 117.

If you'd like to test before my PR before it gets merged (if it does), you can change your _sensor.py_ file to have my changes: [sensor.py](https://raw.githubusercontent.com/tony1661/homeassistant-peloton-sensor/patch-1/custom_components/peloton/sensor.py)

Also, my update also fixed the speed for people using KPH

**Comment by edwork** [comment]
Thanks all,  

Regarding the speed logic, thanks for pointing this out. I'll make sure the changes are released soon.  

Regarding the sensors crashing extra measurements I am working on a larger fix for this because it's not just limited to the heart rate sensor. For example when doing a stretch exercise on your phone, tablet, or TV there are a bunch of objects that don't populate causing further sensors to crash.  

I am planning on putting each statement in a separate try-except where the except will throw a logger.debug message for those who have debugging enabled. 

I'll try to have these changes finished soon, in the meantime look out for updates via HACS (shameless plug for this integration being in the default HACS repo now!).

**Comment by edwork** [comment]
@tony1661 I'm going to merge the PR for both the heart rate monitor setting + speed fix, but I may end up deprecating the setting in favor of the fault tolerant logic.  

I won't push out a release yet but will continue testing with these changes. Keep an eye on the `devel` branch for additional updates. 

Thanks!

**Comment by edwork** [comment]
Please see release 0.7.0 - all problems discussed in this thread should be taken care of. 

https://github.com/edwork/homeassistant-peloton-sensor/releases/tag/0.7.0

Thanks!
